// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.


#include "AutonomousCommand.h"
#include "../Robotmap.h"
#include "../Robot.h"
#include "Timer.h"

AutonomousCommand::AutonomousCommand() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}

// Called just before this Command runs the first time
void AutonomousCommand::Initialize() {
	
}

// Called repeatedly when this Command is scheduled to run
void AutonomousCommand::Execute() {
	AddSequential(new AutoTilt(24.0));
	AddParallel(new AutoRev(1.0),6.5);
	for(int i=0;i<=3;i++) {AddSequential(new AutoFire());}
	AddSequential(new AutoTilt(MIN_TILTER_ANGLE));
	AddSequential(new AutoDrive(0.0,-0.5,0.0),2.0);
}

// Make this return true when this Command no longer needs to run execute()
bool AutonomousCommand::IsFinished() {
	return false;
}

// Called once after isFinished returns true
void AutonomousCommand::End() {
	
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void AutonomousCommand::Interrupted() {

}
