// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.


#include "AutonomousCommand.h"
#include "../Robotmap.h"
#include "../Robot.h"
#include "Timer.h"

AutonomousCommand::AutonomousCommand() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	AddSequential(new AutoRev(1.0));
	AddSequential(new AutoTilt(PYRAMID_SHOT_ANGLE));
	AddSequential(new AutoFire());
	AddSequential(new AutoFire());
	AddSequential(new AutoFire());
	AddSequential(new AutoRev(0.0));
	AddSequential(new AutoTilt(MIN_TILTER_ANGLE));
	AddSequential(new AutoDrive(0.0,-0.4,0.0),2.0);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
