// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.


#include "FireAtWill.h"
#include "../Robotmap.h"
#include "../Robot.h"
#include "../OI.h"
#include "Timer.h"

FireAtWill::FireAtWill(Aim_setting teleopSetting) {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	teleopPreperation=teleopSetting;
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}

// Called just before this Command runs the first time
void FireAtWill::Initialize() {
	
}

// Called repeatedly when this Command is scheduled to run
void FireAtWill::Execute() {
	switch(teleopPreperation)
	{
		default:
			AddSequential(new AutoRev(1.0));
			AddSequential(new AutoTilt(24.0));
		case(Pyramid):
			AddSequential(new AutoRev(1.0));
			AddSequential(new AutoTilt(24.0));
		case(Midcourt): 
			AddSequential(new AutoRev(1.0));
			AddSequential(new AutoTilt(18.0));
		case(Backcourt):
			AddSequential(new AutoRev(1.0));
			AddSequential(new AutoTilt(16.0));
	}
}

// Make this return true when this Command no longer needs to run execute()
bool FireAtWill::IsFinished() {
	return false;
}

// Called once after isFinished returns true
void FireAtWill::End() {
	
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void FireAtWill::Interrupted() {

}
