// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.
package org.usfirst.frc2465.Robot.subsystems;
import org.usfirst.frc2465.Robot.RobotMap;
import org.usfirst.frc2465.Robot.commands.*;
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.command.Subsystem;
/**
 *
 */
public class Tensioner extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    SpeedController leftSC = RobotMap.tensionerLeftSC;
    DigitalInput leftMin = RobotMap.tensionerLeftMin;
    DigitalInput leftMax = RobotMap.tensionerLeftMax;
    AnalogChannel leftDistance = RobotMap.tensionerLeftDistance;
    SpeedController rightSC = RobotMap.tensionerRightSC;
    DigitalInput rightMin = RobotMap.tensionerRightMin;
    DigitalInput rightMax = RobotMap.tensionerRightMax;
    AnalogChannel rightDistance = RobotMap.tensionerRightDistance;
    Solenoid lock = RobotMap.tensionerLock;
    Solenoid unlock = RobotMap.tensionerUnlock;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
}
