// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.


#ifndef TILTER_H
#define TILTER_H
#include "Commands/Subsystem.h"
#include "WPILib.h"
#include "ProximitySensor.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class Tilter: public PIDSubsystem {
private:
	// It's desirable that everything possible under private except
	// for methods that implement subsystem capabilities
public:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	ProximitySensor* height_sensor;
	SpeedController* motor;
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	Tilter();
	void InitDefaultCommand();
	virtual void PIDWrite(float output);

	// PIDSource interface
	virtual double PIDGet();

};

#endif
