// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.


#ifndef OI_H
#define OI_H

#include "WPILib.h"

class OI {
private:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	Joystick* shooter_joystick;
	JoystickButton* rear_climber_hook_up;
	JoystickButton* fire_frisbee;
	JoystickButton* front_climber_hook_up;
	JoystickButton* front_climber_hook_down;
	JoystickButton* rear_climber_hook_down;
	Button* pyramid_prep;
	Button* mid_prep;
	Button* long_prep;
	Joystick* driver_joystick;
	JoystickButton* disable_shooter_drive_control;
	JoystickButton* enable_shooter_drive_control;
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
public:
	OI();
 
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PROTOTYPES

	Joystick* getdriver_joystick();
	Joystick* getshooter_joystick();
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PROTOTYPES
};

#endif
