// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2465.Robot.subsystems;

import org.usfirst.frc2465.Robot.RobotMap;
import org.usfirst.frc2465.Robot.commands.*;
import edu.wpi.first.wpilibj.*;

import edu.wpi.first.wpilibj.command.Subsystem;
import org.usfirst.frc2465.Robot.RobotPreferences;


/**
 *
 */
public class Leg extends Subsystem implements Runnable {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    DigitalInput latched = RobotMap.legLatched;
    DigitalInput ready = RobotMap.legReady;
    Talon SC = RobotMap.legSC;
    Relay lock = RobotMap.tensionerLock;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    int state;
    Thread thread;
    
    public static final int kStateReleased          = 0; 
    public static final int kStateMovingToLatched   = 1; 
    public static final int kStateMovingToReady     = 2;
    public static final int kStateReady             = 3;
    
    public void Leg() {
        
        SC.set(0);
        lock.setDirection(Relay.Direction.kForward);
        lock.set(Relay.Value.kOff);
    }
    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
        thread = new Thread(this);
        //thread.start();
    }
    
    public int getState() {
        return current_state;
    }
    
    // Users can either request kStateReady or kStateReleased
    
    public boolean requestState( int new_state ) {
        
        if ( ( new_state == kStateReady ) || ( new_state == kStateReleased ) )
        {
            requested_state = new_state;
            return true;
        }
        
        return false;
    }

    int requested_state = kStateReady;
    int current_state = kStateReady;
    double ready_motor_speed = RobotPreferences.getLegReadyMotorSpeed();
    double latched_motor_speed = RobotPreferences.getLegLatchedMotorSpeed();
    double update_period_seconds = RobotPreferences.getLegUpdatePeriodSeconds();
    
    public void run() {
        
         boolean is_latched = latched.get();
         boolean is_ready = ready.get();
        
         switch ( requested_state ) {
             
             case kStateReady:
             {
                if ( is_latched ) {
                    if ( !is_ready ) {
                        current_state = kStateMovingToReady;
                        SC.set(ready_motor_speed);
                    }
                    else {
                        current_state = kStateReady;
                        SC.set(0);
                    }
                }
                else {
                    current_state = kStateMovingToLatched;
                    SC.set(latched_motor_speed);
                }                 
             }
             break;
           
             case kStateReleased:
             {
                 if ( is_latched && is_ready ) {
                     lock.set(Relay.Value.kForward);
                 }
                 else {
                     lock.set(Relay.Value.kOff);
                 }
             }
             break;
                 
             default:
                 break;
           
         }
         
        Timer.delay(update_period_seconds);
    }
    
}

