// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.


#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"


// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
SpeedController* RobotMap::swerveDriveSystemmotor = NULL;
AngleSensor* RobotMap::swerveDriveSystemangle_sensor = NULL;
PIDController* RobotMap::swerveDriveSystemfront_left_steer = NULL;
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION

void RobotMap::init() {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
	LiveWindow* lw = LiveWindow::GetInstance();

	swerveDriveSystemmotor = new Talon(1, 1);
	lw->AddActuator("SwerveDriveSystem", "motor", (Talon*) swerveDriveSystemmotor);
	
	swerveDriveSystemangle_sensor = new AngleSensor(1, 14, 13, 12);
	lw->AddSensor("SwerveDriveSystem", "angle_sensor", swerveDriveSystemangle_sensor);
	
	swerveDriveSystemfront_left_steer = new PIDController(1.0, 0.0, 0.0,/* F: 0.0, */ swerveDriveSystemangle_sensor, swerveDriveSystemmotor, 0.02);
	lw->AddActuator("SwerveDriveSystem", "front_left_steer", swerveDriveSystemfront_left_steer);
	swerveDriveSystemfront_left_steer->SetContinuous(false); swerveDriveSystemfront_left_steer->SetAbsoluteTolerance(0.2); 
        swerveDriveSystemfront_left_steer->SetOutputRange(-1.0, 1.0);

	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}
