// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.




#include "Climber.h"
#include "../Robotmap.h"
#include "../Robot.h"
#include "SmartDashboard/SmartDashboard.h"
#include "LiveWindow/LiveWindow.h"

Climber::Climber() : Subsystem("Climber") {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	front_winch_motor = RobotMap::climberfront_winch_motor;
	rear_winch_motor = RobotMap::climberrear_winch_motor;
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	front_climber_solenoid = RobotMap::front_climber_solenoid;
}
    
void Climber::InitDefaultCommand() {
	// Set the default command for a subsystem here.
	//SetDefaultCommand(new MySpecialCommand());
	SetDefaultCommand(new LowerAllHooks());
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
}

void Climber::LowerHooks(){
	RobotMap::climberfront_winch_motor->Set(0);
	RobotMap::climberrear_winch_motor->Set(0);
}

void Climber::LowerFrontHooks(){
	RobotMap::climberfront_winch_motor->Set(0);
	RobotMap::front_climber_solenoid->Set(FALSE);
}

void Climber::LowerRearHooks(){
	RobotMap::climberrear_winch_motor->Set(0);
}

void Climber::RaiseRearHooks(){
	RobotMap::climberrear_winch_motor->Set(1);
}

void Climber::RaiseFrontHooks(){
	RobotMap::climberfront_winch_motor->Set(1);
	RobotMap::front_climber_solenoid->Set(TRUE);
}

// Put methods for controlling this subsystem
// here. Call these from Commands.

