// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.




#include "SwerveDriveSystem.h"
#include "../Robotmap.h"

SwerveDriveSystem::SwerveDriveSystem() : Subsystem("SwerveDriveSystem") {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	left_front_steer_motor = RobotMap::swerveDriveSystemleft_front_steer_motor;
	left_front_angle_sensor = RobotMap::swerveDriveSystemleft_front_angle_sensor;
	left_front_steer = RobotMap::swerveDriveSystemleft_front_steer;
	left_front_rpm_sensor = RobotMap::swerveDriveSystemleft_front_rpm_sensor;
	left_front_drive_motor = RobotMap::swerveDriveSystemleft_front_drive_motor;
	left_front_drive = RobotMap::swerveDriveSystemleft_front_drive;
	right_front_steer_motor = RobotMap::swerveDriveSystemright_front_steer_motor;
	right_front_angle_sensor = RobotMap::swerveDriveSystemright_front_angle_sensor;
	right_front_steer = RobotMap::swerveDriveSystemright_front_steer;
	right_front_rpm_sensor = RobotMap::swerveDriveSystemright_front_rpm_sensor;
	right_front_drive_motor = RobotMap::swerveDriveSystemright_front_drive_motor;
	right_front_drive = RobotMap::swerveDriveSystemright_front_drive;
	left_back_steer_motor = RobotMap::swerveDriveSystemleft_back_steer_motor;
	left_back_angle_sensor = RobotMap::swerveDriveSystemleft_back_angle_sensor;
	left_back_steer = RobotMap::swerveDriveSystemleft_back_steer;
	left_back_rpm_sensor = RobotMap::swerveDriveSystemleft_back_rpm_sensor;
	left_back_drive_motor = RobotMap::swerveDriveSystemleft_back_drive_motor;
	left_back_drive = RobotMap::swerveDriveSystemleft_back_drive;
	right_back_steer_motor = RobotMap::swerveDriveSystemright_back_steer_motor;
	right_back_angle_sensor = RobotMap::swerveDriveSystemright_back_angle_sensor;
	right_back_steer = RobotMap::swerveDriveSystemright_back_steer;
	right_back_drive_motor = RobotMap::swerveDriveSystemright_back_drive_motor;
	right_back_rpm_sensor = RobotMap::swerveDriveSystemright_back_rpm_sensor;
	right_back_drive = RobotMap::swerveDriveSystemright_back_drive;
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
}
    
void SwerveDriveSystem::InitDefaultCommand() {
	// Set the default command for a subsystem here.
	//SetDefaultCommand(new MySpecialCommand());
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
}


// Put methods for controlling this subsystem
// here. Call these from Commands.

