// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2465.GizmoBot;
    
import edu.wpi.first.wpilibj.*;

import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import java.util.Vector;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static DoubleSolenoid lift1LiftValve1;
    public static DoubleSolenoid lift2LiftValve2;
    public static DoubleSolenoid arm1ArmValve3;
    public static DoubleSolenoid arm2ArmValve4;
    public static DoubleSolenoid tilterTilterValve;
    public static DoubleSolenoid stepLiftStepLiftValve;
    public static AnalogInput toteRangerToteRangeSensor;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        lift1LiftValve1 = new DoubleSolenoid(0, 0, 1);      
        LiveWindow.addActuator("Lift1", "LiftValve1", lift1LiftValve1);
        
        lift2LiftValve2 = new DoubleSolenoid(0, 2, 3);      
        LiveWindow.addActuator("Lift2", "LiftValve2", lift2LiftValve2);
        
        arm1ArmValve3 = new DoubleSolenoid(0, 4, 5);      
        LiveWindow.addActuator("Arm1", "ArmValve3", arm1ArmValve3);
        
        arm2ArmValve4 = new DoubleSolenoid(0, 6, 7);      
        LiveWindow.addActuator("Arm2", "ArmValve4", arm2ArmValve4);
        
        tilterTilterValve = new DoubleSolenoid(1, 0, 1);      
        LiveWindow.addActuator("Tilter", "TilterValve", tilterTilterValve);
        
        stepLiftStepLiftValve = new DoubleSolenoid(1, 2, 3);      
        LiveWindow.addActuator("StepLift", "StepLiftValve", stepLiftStepLiftValve);
        
        toteRangerToteRangeSensor = new AnalogInput(0);
        LiveWindow.addSensor("ToteRanger", "ToteRangeSensor", toteRangerToteRangeSensor);
        
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
