// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.


#include "AutoFrontHook.h"

#define HOOK_LOWERED_HEIGHT_INCHES 10
#define HOOK_CLIMBING_HEIGHT_INCHES 15
#define HOOK_AIMING_HEIGHT_INCHES 17

AutoFrontHook::AutoFrontHook(HookLevel hook_level) {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::climber);
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	this->level = hook_level;
	done = false;
}

// Called just before this Command runs the first time
void AutoFrontHook::Initialize() {
	
}

// Called repeatedly when this Command is scheduled to run
void AutoFrontHook::Execute() {
	
	// Invoke the PID controller to set the level to the specified hook level
	// When the target is reached, indicate the command is done.
}

// Make this return true when this Command no longer needs to run execute()
bool AutoFrontHook::IsFinished() {
	return done;
}

// Called once after isFinished returns true
void AutoFrontHook::End() {
	
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void AutoFrontHook::Interrupted() {
	Robot::climber->StopFrontHooks();
}
