// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.


#include "RunCameraGimbal.h"
#include "WPILib.h"
#include "../Robot.h"
#include "../RobotMap.h"

RunCameraGimbal::RunCameraGimbal() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	Requires(Robot::camera);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}

// Called just before this Command runs the first time
void RunCameraGimbal::Initialize() {
	
}

// Called repeatedly when this Command is scheduled to run
void RunCameraGimbal::Execute() {
	//stick1* OI::getshooter_joystick();
	Joystick* p1stick = Robot::oi->getshooter_joystick();
	double azimuth  = p1stick->GetTwist();
	double elevation = p1stick->GetY();
	//Robot::camera->DoCameraGimbal(azimuth,elevation);
	
	
}

// Make this return true when this Command no longer needs to run execute()
bool RunCameraGimbal::IsFinished() {
	return false;
}

// Called once after isFinished returns true
void RunCameraGimbal::End() {
	
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void RunCameraGimbal::Interrupted() {
	float a  = 0;
	float e = 0;
	Robot::camera->DoCameraGimbal(a,e);

}
