#include "SwerveDrive.h"
#include "WPILib.h"
#include "../OI.h"
#include "Joystick.h"
SwerveDrive::SwerveDrive() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::swerveDriveSystem);
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}

// Called just before this Command runs the first time
void SwerveDrive::Initialize() {
	Robot::swerveDriveSystem->EnablePIDControl(true);
}

// Called repeatedly when this Command is scheduled to run
void SwerveDrive::Execute() {  
	Joystick* pstick = Robot::oi->getdriver_joystick();
	double twist = pstick->GetTwist();
	double y = pstick->GetY();
	double x = pstick->GetX();
	Robot::swerveDriveSystem->DoSwerve(x,y,twist);
}

// Make this return true when this Command no longer needs to run execute()
bool SwerveDrive::IsFinished() {
	return false;
}

// Called once after isFinished returns true
void SwerveDrive::End() {
	
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void SwerveDrive::Interrupted() {

}
