// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2465.Robot.commands;

import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc2465.Robot.Robot;
import org.usfirst.frc2465.Robot.RobotPreferences;

/**
 *
 */
public class  SetTension extends Command {

    double tension_volts;
    boolean wait;
    boolean wait_to_finish;
    public SetTension(double volts, boolean wait) {
        // Use requires() here to declare subsystem dependencies
        tension_volts = volts;
        this.wait = wait;
        requires(Robot.tensioner);
	
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called just before this Command runs the first time
    protected void initialize() {
        wait_to_finish = this.wait;
        if ( Robot.kicker.isLegLatchedAndRetractorReady()) {
            Robot.tensioner.setSetpoint(tension_volts);
            Robot.tensioner.enable();
        }
        else {
            wait_to_finish = false;
        }
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        
        if ( !wait_to_finish ) return true;
        if ( Robot.tensioner.onTarget() ) {
            return true;
        }
        return false;
    }

    // Called once after isFinished returns true
    protected void end() {
        Robot.tensioner.disable();
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
        Robot.tensioner.disable();
    }
}
